version: '3.7'

services:
  discordactivitywatcher-api:
    image: 192.168.1.132:5000/discordactivitywatcher-api:1.1.11
    container_name: discordactivitywatcher-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    working_dir: /app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3


  discordactivitywatcher-discordbot:
    image: 192.168.1.132:5000/discordactivitywatcher-discordbot:1.0.6
    container_name: discordactivitywatcher-discordbot
    restart: unless-stopped
    depends_on:
      - discordactivitywatcher-api
    environment:
      - API_BASE_URL
      - DISCORD_TOKEN

  discordactivitywatcher-watcherservice:
    image: 192.168.1.132:5000/discordactivitywatcher-watcherservice:1.0.4
    container_name: discordactivitywatcher-watcherservice
    restart: unless-stopped
    depends_on:
      - discordactivitywatcher-api
    environment:
      - API_BASE_URL