name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    name: Build and publish docker compose
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with Docker Compose
        run: docker-compose -f build-and-publish-compose.yaml build
        
      - name: Push with Docker Compose
        run: docker-compose -f build-and-publish-compose.yaml push
        
  deploy:
    name: Deploy docker compose
    needs: publish
    environment: "Hygge bot"
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Create .env file
        run: |
          echo "API_BASE_URL=${{ vars.API_BASE_URL }}" > .env
          echo "CONNECTION_STRING_DEFAULT=${{ vars.CONNECTION_STRING_DEFAULT }}" > .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_COMMAND }}" >> .env

      - name: Deploy with Docker Compose
        run: docker-compose -f deploy-compose.yaml up -d --force-recreate